# package is named gstreamer-orc to avoid conflicts with apache orc
{% set name = "gstreamer-orc" %}
{% set version = "0.4.41" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/data/src/orc/orc-{{ version }}.tar.xz
  sha256: cb1bfd4f655289cd39bc04642d597be9de5427623f0861c1fc19c08d98467fa2

build:
  number: 0
  run_exports:
    # From: https://gitlab.freedesktop.org/gstreamer/orc/-/blob/0.4.41/README?ref_type=tags
    # The 0.4 series of Orc releases will be API and ABI compatible, and
    # will be incompatible with the 0.5 series when it comes out.
    - {{ pin_subpackage('gstreamer-orc', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
    - meson
    - ninja-base

test:
  commands:
    - test -f $PREFIX/bin/orcc  # [unix]
    - test -f $PREFIX/include/orc-0.4/orc/orc.h  # [unix]
    - test -f $PREFIX/lib/liborc-0.4${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/pkgconfig/orc-0.4.pc  # [unix]
    - if not exist %LIBRARY_BIN%\\orcc.exe exit 1  # [win]
    - if not exist %LIBRARY_INC%\\orc-0.4\\orc\\orc.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\orc-0.4-0.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\orc-0.4.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\orc-0.4.pc exit 1  # [win]

about:
  home: https://gitlab.freedesktop.org/gstreamer/orc
  summary: Orc - Optimized Inner Loop Runtime Compiler
  description: |
    Orc is a library and set of tools for compiling and executing
    very simple programs that operate on arrays of data.  The "language"
    is a generic assembly language that represents many of the features
    available in SIMD architectures, including saturated addition and
    subtraction, and many arithmetic operations.
  license: BSD-2-Clause AND BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  dev_url: https://gitlab.freedesktop.org/gstreamer/orc
  doc_url: https://gitlab.freedesktop.org/gstreamer/orc

extra:
  recipe-maintainers:
    - cbouss
